/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cis240finalproject;

import java.util.ArrayList;

/**
 *
 * @author Jacks
 */
public class SpaceApp extends javax.swing.JFrame {

    /**
     * Creates new form SpaceApp
     */
    public SpaceApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MercuryBTN = new javax.swing.JRadioButton();
        VenusBTN = new javax.swing.JRadioButton();
        EarthBTN = new javax.swing.JRadioButton();
        MarsBTN = new javax.swing.JRadioButton();
        JupiterBTN = new javax.swing.JRadioButton();
        UranusBTN = new javax.swing.JRadioButton();
        SaturnBTN1 = new javax.swing.JRadioButton();
        NeptuneBTN = new javax.swing.JRadioButton();
        PlutoBTN = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SateliteBOX = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OutputTXTBOX = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ReturnCHBOX = new javax.swing.JCheckBox();
        LowOrbitCHBOX = new javax.swing.JCheckBox();
        LandingCHBOX = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MercuryBTN.setText("Mercury");
        MercuryBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MercuryBTNActionPerformed(evt);
            }
        });

        VenusBTN.setText("Venus");

        EarthBTN.setText("Earth");

        MarsBTN.setText("Mars");

        JupiterBTN.setText("Jupiter");

        UranusBTN.setText("Uranus");

        SaturnBTN1.setText("Saturn");

        NeptuneBTN.setText("Neptune");

        PlutoBTN.setText("Pluto");

        SateliteBOX.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(SateliteBOX);

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jButton1.setText("Calculate!");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Satelites");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Destination Planets");

        OutputTXTBOX.setColumns(20);
        OutputTXTBOX.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        OutputTXTBOX.setRows(5);
        OutputTXTBOX.setText("...");
        jScrollPane2.setViewportView(OutputTXTBOX);

        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Modifiers");

        ReturnCHBOX.setText("Return Trip");

        LowOrbitCHBOX.setText("Destination Low Orbit");
        LowOrbitCHBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LowOrbitCHBOXActionPerformed(evt);
            }
        });

        LandingCHBOX.setText("Destination Surface Landing");
        LandingCHBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandingCHBOXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarsBTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JupiterBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UranusBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SaturnBTN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NeptuneBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PlutoBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MercuryBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VenusBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EarthBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(255, 255, 255))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LandingCHBOX)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(LowOrbitCHBOX)
                                    .addContainerGap())
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ReturnCHBOX)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addGap(89, 89, 89)))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ReturnCHBOX))
                        .addGap(18, 18, 18)
                        .addComponent(LowOrbitCHBOX)
                        .addGap(18, 18, 18)
                        .addComponent(LandingCHBOX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(MercuryBTN)
                        .addGap(18, 18, 18)
                        .addComponent(VenusBTN)
                        .addGap(18, 18, 18)
                        .addComponent(EarthBTN)
                        .addGap(18, 18, 18)
                        .addComponent(MarsBTN)
                        .addGap(18, 18, 18)
                        .addComponent(JupiterBTN)
                        .addGap(23, 23, 23)
                        .addComponent(SaturnBTN1)
                        .addGap(18, 18, 18)
                        .addComponent(UranusBTN)
                        .addGap(18, 18, 18)
                        .addComponent(NeptuneBTN)
                        .addGap(18, 18, 18)
                        .addComponent(PlutoBTN))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MercuryBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MercuryBTNActionPerformed
      SateliteBOX.clearSelection();
     
    }//GEN-LAST:event_MercuryBTNActionPerformed

    private void LowOrbitCHBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LowOrbitCHBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LowOrbitCHBOXActionPerformed

    private void LandingCHBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandingCHBOXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LandingCHBOXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        ArrayList<Sattelites> MoonsofMercury = new ArrayList<>();
        Planet Mercury = new Planet ("Mercury", "3.5 months", 20.18, 21.4, 24.46, MoonsofMercury);
        
        ArrayList<Sattelites> MoonsofVenus = new ArrayList<>();
        Planet Venus = new Planet ("Venus", "4.8 months", 12.85, 15.79, 42.79, MoonsofVenus);
        
        ArrayList<Sattelites> MoonsofEarth = new ArrayList<>();
        Planet Earth = new Planet ("Earth", "This is the start point", 0, 0, 0, MoonsofEarth);
        
        ArrayList<Sattelites> MoonsofMars = new ArrayList<>();
        Planet Mars = new Planet ("Mars", "8.5 months", 13.61, 15.05, 18.65, MoonsofMars);
        
        ArrayList<Sattelites> MoonsofJupiter = new ArrayList<>();
        Planet Jupiter = new Planet ("Jupiter", "2.7 years", 15.57, 32.78, 65.78, MoonsofJupiter);
        
        ArrayList<Sattelites> MoonsofSaturn = new ArrayList<>();
        Planet Saturn = new Planet ("Saturn", "6.0 years", 16.71, 26.93, 45.93, MoonsofSaturn);
        
        ArrayList<Sattelites> MoonsofUranus = new ArrayList<>();
        Planet Uranus = new Planet ("Uranus", "16.0 years", 17.49, 23.62, 38.62, MoonsofUranus);
        
        ArrayList<Sattelites> MoonsofNeptune = new ArrayList<>();
        Planet Neptune = new Planet ("Neptune", "30.6 years", 17.6, 24.35, 40.35, MoonsofNeptune);
        
        ArrayList<Sattelites> MoonsofPluto = new ArrayList<>();
        Planet Pluto = new Planet ("Pluto", "45.5 years", 20.06, 20.41, 21.3, MoonsofPluto);
        
        
        Sattelites ISS = new Sattelites (Earth, "Low Earth Orbit (ISS)","20 minutes", 9, 9, 9 );
        
        Sattelites Moon = new Sattelites (Earth, "Moon","2 days", 12.26, 12.94, 14.66 );
        
        Sattelites Phobos = new Sattelites (Mars, "Phobos","8.5 months", 14.89, 14.893, 14.889 );
        
        Sattelites Demios = new Sattelites (Mars, "Demios","8.5 months", 14.6, 14.602, 14.606 );
        
        Sattelites Europa = new Sattelites (Jupiter, "Europa","2.7 years", 24.47, 25.05, 26.49 );
        
        Sattelites Io = new Sattelites (Jupiter, "Io","2.7 years", 25.9, 26.63, 28.41 );
        
        Sattelites Ganymede = new Sattelites (Jupiter, "Ganymede","2.7 years", 22.28, 23.07, 25.02 );
        
        Sattelites Callisto = new Sattelites (Jupiter, "Callisto","2.7 years", 20.72, 21.42, 23.17 );
        
        Sattelites Titan = new Sattelites (Saturn, "Titan","6.0 years", 19.77, 20.43, 28.03 );
        
        Sattelites Enceladus = new Sattelites (Saturn, "Enceladus","6.0 years", 24.81, 24.88, 25.04 );
        
        Sattelites Rhea = new Sattelites (Saturn, "Rhea","6.0 years", 22.62, 22.8, 23.25 );
        
        Sattelites Dione = new Sattelites (Saturn, "Dione","6.0 years", 23.51, 23.65, 24.1 );
        
        Sattelites Tethys = new Sattelites (Saturn, "Tethys","6.0 years", 24.19, 24.3, 24.57);
        
        Sattelites Titania = new Sattelites (Uranus, "Titania","16.0 years", 19.88, 20.1, 20.66);
        
        Sattelites Miranda = new Sattelites (Uranus, "Miranda","16.0 years", 21.97, 22.02, 22.15);
        
        Sattelites Umbriel = new Sattelites (Uranus, "Umbriel","16.0 years", 20.7, 20.85, 21.22);
        
        Sattelites Ariel = new Sattelites (Uranus, "Ariel","16.0 years", 21.12, 21.28, 21.67);
        
        Sattelites Triton = new Sattelites (Neptune, "Triton","30.6 years", 20.1, 20.51, 21.56);
        
        Sattelites Charon = new Sattelites (Pluto, "Charon","45.5 years", 20.12, 20.28, 20.7);
         
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpaceApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EarthBTN;
    private javax.swing.JRadioButton JupiterBTN;
    private javax.swing.JCheckBox LandingCHBOX;
    private javax.swing.JCheckBox LowOrbitCHBOX;
    private javax.swing.JRadioButton MarsBTN;
    private javax.swing.JRadioButton MercuryBTN;
    private javax.swing.JRadioButton NeptuneBTN;
    private javax.swing.JTextArea OutputTXTBOX;
    private javax.swing.JRadioButton PlutoBTN;
    private javax.swing.JCheckBox ReturnCHBOX;
    private javax.swing.JList<String> SateliteBOX;
    private javax.swing.JRadioButton SaturnBTN1;
    private javax.swing.JRadioButton UranusBTN;
    private javax.swing.JRadioButton VenusBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
